// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thoscfdddjqrqpwbghxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRob3NjZmRkZGpxcnFwd2JnaHhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MTE1MDYsImV4cCI6MjA2NDQ4NzUwNn0.tlthVoSBpXokubluGE-MwtCiP5D1NVuqSOmyYu_gmzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);